### ISSUE TITLE
Segmentation fault in qrouter 1.4.71

### ISSUE THREAD

**Issue by just22** [RTimothyEdwards/qrouter#2]
Dear Tim,

Trying to update qrouter's OpenBSD port from 1.4.50 to the latest 
version (1.4.71), I'm facing segmentation faults at lines 3480 and 3515 
of node.c; the code, for both lines, is:
```
lnode = NODEIPTR(gridx, gridy, lds.layer);
```
gdb says that gridy is equal to -1 each time the program segfaults, so I 
suspect that a negative value cannot be managed by NODEIPTR.

With the following patch:

```
Index: node.c
--- node.c.orig
+++ node.c
@@ -3476,6 +3477,7 @@ find_route_blocks()
  		     dy += PitchY;
  		     gridy++;
  		  }
+		  if (gridy < 0) gridy = 0;
  		  while (dy < lds.y2 + s) {
  		     lnode = NODEIPTR(gridx, gridy, lds.layer);
  		     u = ((OBSVAL(gridx, gridy, lds.layer) & STUBROUTE)
@@ -3511,6 +3513,7 @@ find_route_blocks()
  		     dy += PitchY;
  		     gridy++;
  		  }
+		  if (gridy < 0) gridy = 0;
  		  while (dy < lds.y2 + s) {
  		     lnode = NODEIPTR(gridx, gridy, lds.layer);
  		     u = ((OBSVAL(gridx, gridy, lds.layer) & STUBROUTE)
```

I'm able to complete the routing on map9v3 example block, but of course 
I don't know if this is the right thing to do...

All the best

--
Alessandro De Laurenzis

**Comment by RTimothyEdwards** [comment]
Almost. . . you don't want to just set gridy to zero there because dy (the location in microns) and gridy (the location in route grid index) have to match.  However, the code just above that point in both locations is incrementing the gridy position until it is inside the blockage, so it is very easy to add the condition there that gridy must be greater than or equal to zero.  Also, since that subroutine checks blockages in all directions, the same change should be made to the east-west checks to make sure that gridx is not negative.  I have patched the code and pushed to the git repo on opencircuitdesign.com.  The github repo is a mirror repo that is updated every night, so the correction won't show up here for another 13 hours.

Thanks for the bug report and patch!

---Tim

**Comment by just22** [comment]
Hello Tim,

just double checked with v.1.4.73. Problem solved, thanks for your prompt reaction.

Closing.

--
Alessandro
